#NOTICE: If any error occurs while running this scirpt, run "MSP_data_processing_1.R" again and then run this script. Some data generated by previous script may be necessary for running this script.

#enter directory location
directory <- "~/Desktop/R Scripts"
#specify mass spec samples, replicates should be denoted with the same numbers
sample <- c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4)
#Optioanl, whether to fix random numbers
set.seed(123)
numsample <- length(sample)
library(data.table)
library(qvalue)
library(fitdistrplus)
library(truncnorm)
library(gtools)
library(outliers)
#set working directory, all files should be in this directory
setwd(directory)

samplestr <- table(sample)
timept <- NULL
fccolnames <- NULL
for (i in 1:length(samplestr)){
        timept <- c(timept,as.numeric(samplestr[names(samplestr)==i]))
}


data <- read.csv("protein-peptides_outlier_rm.csv", sep = ",", header=TRUE, row.names = NULL, stringsAsFactors = FALSE)
#imputation method, normal distribution model, normally distributed within smalles 5%
ls<-NULL
for(i in 1:nrow(data)){
        ls <- c(ls, data[i,1:9],as.numeric(gsub("NA", 0, data[i,10:(9+numsample)])))
}
data7 <- as.matrix.data.frame(matrix(ls,ncol=(9+numsample),byrow=TRUE))
colnames(data7) <- c(colnames(data[,1:(9+numsample)]))
v1<-as.numeric(as.matrix(data7[,10:(9+numsample)]))
v2<-v1[v1 != 0]
v3<-tail(sort(v2, decreasing=TRUE), noise*length(v2))
fit.norm <- fitdistr(v3, "normal")
mean <- fit.norm$estimate[[1]]
sd <- fit.norm$estimate[[2]]
max <- fit.norm$estimate[[1]]+nsd*fit.norm$estimate[[2]]
min <- fit.norm$estimate[[1]]-nsd*fit.norm$estimate[[2]]
for (i in 1:nrow(data7)){
        counter = 9
        for (j in 1:length(timept)){
                counter1 = counter + timept[j]
                #impute missing values only when one or no datum is present
                if ((timept[j] - sum(is.na(data[i,(counter+1):counter1]))) < 2){
                        r.norm <- round(rtruncnorm(sum(is.na(data[i,(counter+1):counter1])),a = min, b = max, mean,sd),0)
                        data7[i,(counter+1):counter1][data7[i,(counter+1):counter1] == 0] <- r.norm
                }
                data7[i,(counter+1):counter1][data7[i,(counter+1):counter1] == 0] <- NA
                counter <- counter1
        }
}
write.csv(data7, file = "protein-peptides_imputed.csv", append = FALSE,  sep = ",", row.names = FALSE)

#extract 8-mer cleavage sequences
data <- read.csv("protein-peptides_imputed.csv", sep = ",", header=TRUE, row.names = NULL, stringsAsFactors = FALSE)
#read TDP_237library_forR.txt, file need to be in the directory, then generate reference list
ref <- readLines("TDP_237library_forR.txt")
reftab <- NULL
reftab <- matrix(ref,ncol=3,byrow=TRUE)
outseq <- data$Peptide
seqs <- data$Peptide
seqs <- toupper(seqs)
seqs <- gsub(".", "", seqs, fixed = TRUE)
seqs1 <- data$Peptide
seqs1 <- toupper(seqs1)
seqs1 <- gsub(".", "_", seqs1, fixed = TRUE)
refseqs <- NULL
for(i in 1:length(seqs)){
        refseqs <- c(refseqs, reftab[grep(seqs[i], reftab[,2]), ], seqs1[i])
}
refseqs <- matrix(refseqs,ncol=4,byrow=TRUE)
#searching for cleavage loci
nterm <- NULL
cterm <- NULL
cleavespots <- NULL
temp1 <- NULL
temp2 <- NULL
for(i in 1:length(seqs1)){
        temp1<-""
        if((grepl("_", seqs1[i])==TRUE) && (regexpr('_',seqs1[i])[[1]][1]==2)){
                pos1 <- regexpr('_',seqs1[i])[[1]][1]
                temp <- substr(seqs1[i],pos1+1, pos1+3)
                pos1 <- regexpr(temp,refseqs[i,2])[[1]][1]
                temp1 <- pos1 - 1
                if(pos1 == 2){
                        nterm[i] <- paste(c("XXX", substr(refseqs[i,3],1,5)),collapse = "")
                }
                if(pos1 == 3){
                        nterm[i] <- paste(c("XX", substr(refseqs[i,3],1,6)),collapse = "")
                }
                if(pos1 == 4){
                        nterm[i] <- paste(c("X", substr(refseqs[i,3],1,7)),collapse = "")
                }
                if(pos1 == 5||pos1 == 6||pos1 == 7||pos1 == 8||pos1 == 9||pos1 == 10||pos1 == 11){
                        nterm[i] <- substr(refseqs[i,3],pos1-4,pos1+3)
                }
                if(pos1 == 12){
                        nterm[i] <- paste(c(substr(refseqs[i,3],7,14), "X"),collapse = "")
                }
        }
        
        if((grepl("_", seqs1[i])==TRUE) && (regexpr('_',seqs1[i])[[1]][1]==nchar(seqs1[i])-1)){
                end <- nchar(seqs1[i])
                pos2 <- gregexpr('_',seqs1[i])[[1]][1]
                temp <- substr(seqs1[i],pos2-3, pos2-1)
                pos2 <- (regexpr(temp,refseqs[i,2])[[1]][1]) + 3
                temp1 <- pos2 - 1
                if(pos2 == 14){
                        cterm[i] <- paste(c(substr(refseqs[i,3],10,14), "XXX"),collapse = "")
                }
                if(pos2 == 13){
                        cterm[i] <- paste(c(substr(refseqs[i,3],9,14), "XX"),collapse = "")
                }
                if(pos2 == 12){
                        cterm[i] <- paste(c(substr(refseqs[i,3],8,14), "X"),collapse = "")
                }
                if(pos2 == 5||pos2 == 6||pos2 == 7||pos2 == 8||pos2 == 9||pos2 == 10||pos2 == 11){
                        cterm[i] <- substr(refseqs[i,3],pos2-4,pos2+3)
                }
                if(pos2 == 4){
                        cterm[i] <- paste(c("X", substr(refseqs[i,3],1,7)),collapse = "")
                }
        }
        
       if((grepl("_", seqs1[i])==TRUE) && (is.na(gregexpr("_", seqs1[i])[[1]][2])==FALSE)){
                end <- nchar(seqs1[i])
                pos3 <- gregexpr("_", seqs1[i])[[1]][2]
                temp <- substr(seqs1[i],pos3-3, pos3-1)
                pos3 <- (regexpr(temp,refseqs[i,2])[[1]][1]) + 3
                temp2 <- pos3 - 1
                if(pos3 == 14){
                        cterm[i] <- paste(c(substr(refseqs[i,3],10,14), "XXX"),collapse = "")
                }
                if(pos3 == 13){
                        cterm[i] <- paste(c(substr(refseqs[i,3],9,14), "XX"),collapse = "")
                }
                if(pos3 == 12){
                        cterm[i] <- paste(c(substr(refseqs[i,3],8,14), "X"),collapse = "")
                }
                if(pos3 == 5||pos3 == 6||pos3 == 7||pos3 == 8||pos3 == 9||pos3 == 10||pos3 == 11){
                        cterm[i] <- substr(refseqs[i,3],pos2-4,pos2+3)
                }
                if(pos3 == 4){
                        cterm[i] <- paste(c("X", substr(refseqs[i,3],1,7)),collapse = "")
                }
	}
       if (is.na(gregexpr("_", seqs1[i])[[1]][2])==FALSE){
               cleavespots <- c(cleavespots, paste(temp1,";",temp2))
       }else{
               cleavespots <- c(cleavespots, temp1)
       }
}

cleave <- NULL
for(i in 1:length(seqs1)){
        cleave <- c(cleave, refseqs[i,1], refseqs[i,2], refseqs[i,3], outseq[i], nterm[i], cterm[i], 
        cleavespots[i], data[i, 7:ncol(data)])
}

cleavetab <- as.matrix.data.frame(matrix(cleave,ncol=(ncol(data)+1),byrow=TRUE))
colnames(cleavetab) <- c("Protein", "MatchSequence","RealSequence", "Annotated_Sequence", "N-term", "C-term",
"Cleave_Loc", colnames(data[7:ncol(data)]))
write.csv(cleavetab, file = "protein-peptides_prepared.csv", append = FALSE,  sep = ",", row.names = FALSE)